[package]
name = "fekit-cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "fekit"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
regex = "1.11.1"
console = "0.15.8"
